export const books = [
  {
    id: 1,
    judul: "Laskar Pelangi",
    author: "Andrea Hirata",
    publisher: "Bentang Pustaka",
    tahun: 2005,
    kategori: "Novel",
    bahasa: "Indonesia",
    halaman: 529,
    isbn: "9789793062797",
    sinopsis: "Bercerita tentang perjuangan anak-anak miskin di Belitung dalam meraih pendidikan dan cita-cita mereka.",
    cover: "https://placehold.net/600x800.png",
    lokasi: "Rak A1",
    tersedia: true,
    stok: 3,
    rating: 4.8,
    tags: ["inspiratif", "pendidikan", "persahabatan"],
  },
  {
    id: 2,
    judul: "To Kill a Mockingbird",
    author: "Harper Lee",
    publisher: "J.B. Lippincott & Co.",
    tahun: 1960,
    kategori: "Classic",
    bahasa: "English",
    halaman: 324,
    isbn: "9780061120084",
    sinopsis: "Sebuah kisah moral dan keadilan di Amerika Selatan yang penuh dengan nilai kemanusiaan.",
    cover: "https://placehold.net/600x800.png",
    lokasi: "Rak C3",
    tersedia: false,
    stok: 0,
    rating: 4.9,
    tags: ["moral", "humanity", "classic"],
  },
  {
    id: 3,
    judul: "Pemrograman JavaScript Modern",
    author: "Eko Kurniawan Khannedy",
    publisher: "Informatika",
    tahun: 2020,
    kategori: "Teknologi",
    bahasa: "Indonesia",
    halaman: 412,
    isbn: "9786020464532",
    sinopsis: "Panduan komprehensif untuk memahami JavaScript dari dasar hingga konsep modern seperti async dan module.",
    cover: "https://placehold.net/600x800.png",
    lokasi: "Rak T2",
    tersedia: true,
    stok: 5,
    rating: 4.6,
    tags: ["programming", "javascript", "web development"],
  },
  {
    id: 4,
    judul: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    publisher: "Harper",
    tahun: 2015,
    kategori: "Sejarah",
    bahasa: "English",
    halaman: 498,
    isbn: "9780062316097",
    sinopsis: "Menelusuri sejarah panjang manusia dari zaman purba hingga era modern dengan perspektif ilmiah dan filosofis.",
    cover: "https://placehold.net/600x800.png",
    lokasi: "Rak H1",
    tersedia: true,
    stok: 2,
    rating: 4.7,
    tags: ["history", "evolution", "anthropology"],
  },
  {
    id: 5,
    judul: "Filosofi Teras",
    author: "Henry Manampiring",
    publisher: "Kompas",
    tahun: 2018,
    kategori: "Filsafat",
    bahasa: "Indonesia",
    halaman: 320,
    isbn: "9786024811165",
    sinopsis: "Pengenalan konsep stoisisme untuk membantu pembaca mengelola emosi dan berpikir rasional di kehidupan modern.",
    cover: "https://placehold.net/600x800.png",
    lokasi: "Rak F1",
    tersedia: true,
    stok: 4,
    rating: 4.5,
    tags: ["filsafat", "motivasi", "stoicism"],
  },
  {
    id: 6,
    judul: "Clean Code: A Handbook of Agile Software Craftsmanship",
    author: "Robert C. Martin",
    publisher: "Prentice Hall",
    tahun: 2008,
    kategori: "Teknologi",
    bahasa: "English",
    halaman: 464,
    isbn: "9780132350884",
    sinopsis: "Panduan menulis kode yang bersih, efisien, dan mudah dipahami dalam pengembangan perangkat lunak modern.",
    cover: "https://placehold.net/600x800.png",
    lokasi: "Rak T4",
    tersedia: false,
    stok: 0,
    rating: 4.9,
    tags: ["software engineering", "best practices", "clean code"],
  },
];
